server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: selfserveapp13@gmail.com
    password: kulotte2008
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

config:
  securite:
    active: false
  styles:
    images:
      path: "\\src\\main\\resources\\img\\"

front-end:
  url : "http://localhost:3000"

security:
  jwt:
    duration: 5

stripe:
  apiKey: "sk_test_51HLwKgC5UoZOX4GRUFItjFyJNULwHrPtVdQneYTfdNWN8Jvaix5wabpNZk8JwjkSG36Mg2st9yV1VrhnfhUfhAOQ00NasvN6m1"
